export const ACTIONS = {
  FETCH_DATA: "FETCH_DATA",
  FILTER_BY_CODE: "FILTER_BY_CODE",
  FILTER_BY_ID: "FILTER_BY_ID",
  GROUP_BY_CODE: "GROUP_BY_CODE",
  GROUP_BY_YEAR: "GROUP_BY_YEAR",
  GROUP_BY_MONTH: "GROUP_BY_MONTH",
  DISABLE_GROUP_BY_CODE: "DISABLE_GROUP_BY_CODE",
  DISABLE_GROUP_BY_YEAR: "DISABLE_GROUP_BY_YEAR",
  DISABLE_GROUP_BY_MONTH: "DISABLE_GROUP_BY_MONTH",
};
